### PR TITLE
chore: add a way to specify --public-url in npm run

### PR DESCRIPTION
**Pull request by KazuCocoa**
We'd like to customize `--public-url` argument with npm run command like below:

`PUBLIC_URL=/appium-inspector npm run build:browser`

to customize the built package's path related information to a specific subdirectory.

Or would it be nice to create the same one to appium/appium-inspector? @jlipps  (not sure if this helps in the appium/appium-inspector as well)

### CODE REVIEW

**Comment by kazzmir** [comment]
looks good

**Comment by KazuCocoa** [comment]
oh, i should handle something for Win env to bring this change to the upstream. This PR itself is ok for the xUnix env

```
> appium-inspector@2023.10.4 build:browser
> PUBLIC_URL=. npm run build:browser:url

'PUBLIC_URL' is not recognized as an internal or external command,
operable program or batch file.
```

**Review by jlipps — COMMENTED** [review]
yeah no reason this can't go in the upstream fork

**Comment by jlipps** [comment]
i think `cross-env` might help ?

**Comment by KazuCocoa** [comment]
seems good, let me create the same change to the upstream instead of this pr

**Pull request closed without merging**
