### PR TITLE
PROD-8650: adding nvmrc version for appium-inspector

### PR DESCRIPTION
**Pull request by esunheadspin**
adding .nvmrc to our fork of appium-inspector

### CODE REVIEW

**Review by iepathos — APPROVED** [review]
lgtm

**Comment by esunheadspin** [comment]
@KazuCocoa hey i've set the node version on V1 4 but it seems that the checks are at V20 I'm unsure if what I'm doing here is right

**Comment by KazuCocoa** [comment]
NodeJS 14 build env would get issues. We (as appium team) use nodejs 18 as min engine version, so no one tested them with nodejs 14 env. I guess... recent appium-inspector might get an issue with such an old node/npm build environment.
https://github.com/appium/appium-inspector/blob/main/package.json
https://github.com/projectxyzio/appium-inspector/blob/main/package.json

(I guessed this primary usage was for module building)

**Review by KazuCocoa — APPROVED** [review]
When the inspector's original one bumps up the version, shall I bump this lib as well as part of updating this repository, or would it be good to notifying you without modifying this file? @esunheadspin

**Comment by esunheadspin** [comment]
> When the inspector's original one bumps up the version, shall I bump this lib as well as part of updating this repository, or would it be good to notifying you without modifying this file? @esunheadspin

I don't think it's strictly necessary to notify us as long as the version gets changed in the .nvmrc because that's what we planned to happen so that we don't have to keep track of these things and they will work for whatever version they are set at for that specific version with a certain commit sha sum

my main concern is that the PR Validation for macos-latest is taking forever and unable to let me update the repo

**Comment by KazuCocoa** [comment]
Hm, I'll take a look at the CI failure.
The original one succeeded with the macos-latest... https://github.com/appium/appium-inspector/actions/runs/10478708035/job/29022686939

We our usage, the important thing is for browser usage, thus we could simplify the CI for this repo's usage.

**Comment by esunheadspin** [comment]
right now the CI tests are set at node version 20 which I'm unsure of whether that's intentional or accidental
does appium-inspector work with node V20? right now i'm assuming the CI is set to install node to the latest which had issues in pbox and platform

**Comment by KazuCocoa** [comment]
It is intentional. The inspector’s build env doesn’t need to be the mini version, thus CI runs with latest LTS to test out latest env

**Comment by esunheadspin** [comment]
@KazuCocoa  is it okay that the Macos CI tests is failing?
since this is just setting a v18 node version here we should be good to merge right?

**Pull request merged**
